#!/usr/bin/env bash

# GNOME settings for Fedora

# A11y settings
gsettings set org.gnome.desktop.a11y \
  always-show-universal-access-status true

# Input sources
gsettings set org.gnome.desktop.input-sources \
  xkb-options "['compose:menu', 'lv3:rwin_switch']"

# Interface settings
gsettings set org.gnome.desktop.interface \
  clock-format "24h"

gsettings set org.gnome.desktop.interface \
  clock-show-weekday true

gsettings set org.gnome.desktop.interface \
  enable-hot-corners false

gsettings set org.gnome.desktop.interface \
  show-battery-percentage true

# Touchpad settings
gsettings set org.gnome.desktop.peripherals.touchpad \
  natural-scroll false

gsettings set org.gnome.desktop.peripherals.touchpad \
  tap-to-click true

# Privacy settings
gsettings set org.gnome.desktop.privacy \
  remove-old-temp-files true

gsettings set org.gnome.desktop.privacy \
  remove-old-trash-files true

# Window management keybindings
gsettings set org.gnome.desktop.wm.keybindings \
  close "['<Alt>F4', '<Super>Q']"

gsettings set org.gnome.desktop.wm.keybindings \
  move-to-center "['<Ctrl><Super>C']"

gsettings set org.gnome.desktop.wm.keybindings \
  switch-applications "['<Super>Tab']"

gsettings set org.gnome.desktop.wm.keybindings \
  switch-applications-backward "['<Shift><Super>Tab']"

gsettings set org.gnome.desktop.wm.keybindings \
  switch-windows "['<Alt>Tab']"

gsettings set org.gnome.desktop.wm.keybindings \
  switch-windows-backward "['<Shift><Alt>Tab']"

# Window preferences
gsettings set org.gnome.desktop.wm.preferences \
  button-layout "appmenu:close"

# Mutter settings
gsettings set org.gnome.mutter \
  attach-modal-dialogs false

gsettings set org.gnome.mutter \
  center-new-windows true

gsettings set org.gnome.mutter \
  edge-tiling false

# Media keys
gsettings set org.gnome.settings-daemon.plugins.media-keys \
  calculator "['<Super>C']"

gsettings set org.gnome.settings-daemon.plugins.media-keys \
  control-center "['<Super>comma']"

gsettings set org.gnome.settings-daemon.plugins.media-keys \
  email "[]"

gsettings set org.gnome.settings-daemon.plugins.media-keys \
  home "['<Super>F']"

gsettings set org.gnome.settings-daemon.plugins.media-keys \
  www "['<Super>B']"

# Power settings
gsettings set org.gnome.settings-daemon.plugins.power \
  power-button-action 'interactive'

gsettings set org.gnome.settings-daemon.plugins.power \
  sleep-inactive-ac-type 'nothing'

# Workspace keybindings
gsettings set org.gnome.desktop.wm.keybindings \
  switch-to-workspace-left "['<Super>Page_Up', '<Super><Alt>Left', '<Control><Alt>Left']"

gsettings set org.gnome.desktop.wm.keybindings \
  switch-to-workspace-right "['<Super>Page_Down', '<Super><Alt>Right', '<Control><Alt>Right']"

for number in 1 2 3 4 5 6 7 8 9 ; do
  gsettings set org.gnome.desktop.wm.keybindings \
    switch-to-workspace-${number} "['<Super>${number}', '<Super>KP_${number}']"
done

# Disable application switching with Super+[number]
for number in 1 2 3 4 5 6 7 8 9 ; do
  gsettings set org.gnome.shell.keybindings \
    switch-to-application-${number} "[]"
done

# Software settings
gsettings set org.gnome.software \
  packaging-format-preference "['rpm', 'flatpak:fedora-testing', 'flatpak:fedora']"

gsettings set org.gnome.software \
  show-only-free-apps false
