#!/usr/bin/env bash

source /etc/os-release

##################
# GNOME Settings #
##################

#
# Common
#
gsettings set org.gnome.desktop.input-sources \
  xkb-options \
  "['compose:menu', 'lv3:rwin_switch']"

gsettings set org.gnome.desktop.interface \
  clock-format \
  "24h"

gsettings set org.gnome.desktop.interface \
  clock-show-weekday \
  true

gsettings set org.gnome.desktop.interface \
  enable-hot-corners \
  false

gsettings set org.gnome.desktop.interface \
  show-battery-percentage \
  true

gsettings set org.gnome.desktop.peripherals.touchpad \
  natural-scroll \
  false

gsettings set org.gnome.desktop.peripherals.touchpad \
  tap-to-click \
  true

gsettings set org.gnome.desktop.privacy \
  remove-old-temp-files \
  true

gsettings set org.gnome.desktop.privacy \
  remove-old-trash-files \
  true

gsettings set org.gnome.desktop.wm.keybindings \
  close \
  "['<Alt>F4', '<Super>Q']"

gsettings set org.gnome.desktop.wm.keybindings \
  move-to-center \
  "['<Ctrl><Super>C']"

gsettings set org.gnome.desktop.wm.keybindings \
  switch-applications \
  "['<Super>Tab']"

gsettings set org.gnome.desktop.wm.keybindings \
  switch-applications-backward \
  "['<Shift><Super>Tab']"

gsettings set org.gnome.desktop.wm.keybindings \
  switch-windows \
  "['<Alt>Tab']"

gsettings set org.gnome.desktop.wm.keybindings \
  switch-windows-backward \
  "['<Shift><Alt>Tab']"

gsettings set org.gnome.desktop.wm.preferences \
  button-layout \
  "appmenu:close"

gsettings set org.gnome.mutter \
  attach-modal-dialogs \
  false

gsettings set org.gnome.mutter \
  center-new-windows \
  true

gsettings set org.gnome.mutter \
  edge-tiling \
  false

gsettings set org.gnome.settings-daemon.plugins.media-keys \
  calculator \
  "['<Super>C']"

gsettings set org.gnome.settings-daemon.plugins.media-keys \
  control-center \
  "['<Super>comma']"

gsettings set org.gnome.settings-daemon.plugins.media-keys \
  email \
  "[]"

gsettings set org.gnome.settings-daemon.plugins.media-keys \
  home \
  "['<Super>F']"

gsettings set org.gnome.settings-daemon.plugins.media-keys \
  www \
  "['<Super>B']"

gsettings set org.gnome.settings-daemon.plugins.power \
  power-button-action \
  'interactive'

gsettings set org.gnome.settings-daemon.plugins.power \
  sleep-inactive-ac-type \
  'nothing'

for number in 1 2 3 4 5 6 7 8 9 ; do
  gsettings set org.gnome.desktop.wm.keybindings \
    switch-to-workspace-${number} \
    "['<Super>${number}', '<Super>KP_${number}']"
done

for number in 1 2 3 4 5 6 7 8 9 ; do
  gsettings set org.gnome.shell.keybindings \
    switch-to-application-${number} \
    "[]"
done

#
# Fedora
#
if [ "${NAME}" == "Fedora" ] ; then
  gsettings set org.gnome.desktop.a11y \
    always-show-universal-access-status \
    true

  gsettings set org.gnome.software \
    packaging-format-preference \
    "['rpm', 'flatpak:fedora-testing', 'flatpak:fedora']"

  gsettings set org.gnome.software \
    show-only-free-apps \
    true
fi

#
# Pop!_OS
#
if [ "${NAME}" == "Pop!_OS" ] ; then
  gsettings set org.gnome.shell.extensions.pop-shell \
    toggle-tiling \
    "[]"

  gsettings set org.gnome.shell.extensions.pop-shell \
    focus-down \
    "['<Super>Down', '<Super>j']"

  gsettings set org.gnome.shell.extensions.pop-shell \
    focus-left \
    "['<Super>Left', '<Super>h']"

  gsettings set org.gnome.shell.extensions.pop-shell \
    focus-right \
    "['<Super>Right', '<Super>l']"

  gsettings set org.gnome.shell.extensions.pop-shell \
    focus-up \
    "['<Super>Up', '<Super>k']"
fi
